spring:
  datasource:
     url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver


#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.springboot.domain.
